### ISSUE TITLE
Guns does not want to fire.

### ISSUE THREAD

**Issue by spadedzero** [jongshh/BDArmory#1]
**Describe the bug**
When using the 20mm Vulcan (hidden) or the 25mm GAU-22A with their respective ammo types, the bottom left corner says "ammo depleted" and the guns do not want to fire when trying to shoot.

**To Reproduce**
Use the GAU-22A or vulcan (hidden) on your craft with its ammo type (25x137)

**Expected behavior**
Guns don't want to fire.

**Logs**
https://ln5.sync.com/dl/fb138ae90/ckwjs2w7-4bxf47cd-9ijmw3xy-axvythuq

**Screenshots**
![Screenshot 2024-10-11 112150](https://github.com/user-attachments/assets/828dde8e-d02e-4c4d-a5c6-b61222605b6d)
*when idle*
![Screenshot 2024-10-11 112216](https://github.com/user-attachments/assets/c39f7f8c-7eb8-4ebd-850f-ae07df0fcabd)
*when holding down the left mouse button to shoot*

**Comment by jongshh** [comment]
First, I launched the game with v1.0.0 and checked the hidden Vulcan and GAU-22A. Both the default settings and ammo usage were working fine for me.

I checked your log and found that this error was repeating:

```
NullReferenceException: Object reference not set to an instance of an object
	BDArmory.Utils.ProceduralWing.GetPWingVolume (Part part) (at <32e60d99ef9d49b9bd7e0bd6e824bd8e>:0)
	BDArmory.Damage.HitpointTracker.CalculateTotalHitpoints () (at <32e60d99ef9d49b9bd7e0bd6e824bd8e>:0)
	BDArmory.Damage.HitpointTracker.SetupPrefab () (at <32e60d99ef9d49b9bd7e0bd6e824bd8e>:0)
	BDArmory.Damage.HitpointTracker.RefreshHitPoints () (at <32e60d99ef9d49b9bd7e0bd6e824bd8e>:0)
	BDArmory.Damage.HitpointTracker.Update () (at <32e60d99ef9d49b9bd7e0bd6e824bd8e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

If your previous BDArmory version was working fine, the issue is likely related to the Procedural Wing-based hitpoint calculations. This method seems to have an error, which might also prevent the firing method from being called.

Here are some steps you can try:

1. **Try BDArmory's latest version**:  
   [Download here](https://github.com/BrettRyland/BDArmory/releases/tag/v1.7.1.0).  
   If the problem persists, proceed to step 2.  
   If this version fixes the issue, let me know.

2. **Update your Procedural Wing**:  
   This issue is commonly associated with the procedural wing, so update it to the latest version:  
   [Download here](https://github.com/B9-Procedural-Wings/B9-PWings-Modified/releases/tag/0.46.0).
   
3. **Update NMB to v3.9**
   The error you reported has been addressed and fixed before. It was related to the Nice MKseries Body, although we don’t 
   know the exact cause. However, updating that also resolves the issue.
   Check it out!

If needed, you can also download the connected moving wing fix from the technique-share section on my Discord server.

**Comment by spadedzero** [comment]
I tried everything in your previous post and still have the same issue.

**Comment by jongshh** [comment]
If Original mod didn't fix the issue, It's not this mods problem.

Check another mods that conflict with bdarmory's update (mostly addon mods)

> I tried everything in your previous post and still have the same issue.

**Comment by spadedzero** [comment]
I went through all of my mods individually and it turns out that it was the procedural wings mod. I've tried multiple versions of the procedural wings mod but the gun still won't fire. Is it possible for you to share the procedural wings mod version that you are currently using?

**Comment by spadedzero** [comment]
I figured out that I could fix the 20mm Vulcan by reapplying the same gun to the craft to update the part. This issue happens on some craft with the 20mm. However, the GAU-22 has a similar but different issue. Some craft with the GAU-22 work without reapplying the gun, but other craft won't shoot the GAU-22 even if I reapply the ammo and gun. I also noticed that there are parts in some crafts that cause the issue when comparing them to crafts that work with the same gun, but I can't identify the part causing the issue.

https://ln5.sync.com/dl/a05d6ac30/qspfq5pm-cdhpywmz-2s787r3r-44g3ty5a
(link to the updated KSP.log and the crafts mentioned in the comment)

**Comment by spadedzero** [comment]
UPDATE
I finally fixed the issue. I noticed that if you put the GAU-22 on any procedural wing (at least on my version), you will encounter the problem that I've been having. To fix it, you have to attach the GAU-22 on any part besides the procedural wings.
